sudo: required
services:
  - docker

before_install:
  - docker build -t maracartman/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true maracartman/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-sa-east-1-768964238245
  bucket_path: docker-react
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "AWS_SECRET_KEY"